#include "frontend_main.h"

#include "controls.h"
#include "frontend.h"
#include "frontend_changecar.h"
#include "frontend_network.h"
#include "frontend_newgame.h"
#include "frontend_options.h"
#include "frontend_quit.h"
#include "frontend_wrecks.h"
#include "globvars.h"
#include "globvrpb.h"
#include "graphics.h"
#include "input.h"
#include "loading.h"
#include "main.h"
#include "network.h"
#include "platform.h"
#include "polyfont.h"
#include "racestrt.h"
#include "utility.h"

#include "c2_string.h"
void C2_HOOK_FASTCALL FuckingMakeTheFuckingRaceAndGroupsDisplayHaveTheRightCuntingStuffInIt(tFrontend_spec* pFrontend);